/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciocaracteres1;

/**
 *
 * @author david
 */
public class FrmEjerciciocaracteres1 extends javax.swing.JFrame {
    String [] articulos = {"El","Un","Algun","Ningùn"};
    String [] articulos1 = {"el","un","algun","ningùn"};
    String [] sustantivos = {"niño","niña","perro","ciudad","auto"};
    String [] verbos = {"manejo","salto","corrio","camino","omitio"};
    String [] preposiciones = {"a", "desde", "encima de", "debajo de","sobre"};
    int posarticulo;
    int posarticulo1;
    int possustantivo;
    int possustantivo1;
    int posverbo;
    int pospreposicion;
    char Mayuscula;
    char articulo;
   
    /**
     * Creates new form FrmEjerciciocaracteres1
     */
    public FrmEjerciciocaracteres1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRandom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRandom.setText("Oración Randómica");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(btnRandom)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
    //   Articulo, sustantivo, verbo, preposición, articulo y sustantivo.
    posarticulo= (int) (Math.random()*4);
    posarticulo1= (int) (Math.random()*4);
    possustantivo = (int) (Math.random()*6);
    possustantivo1 = (int) (Math.random()*6);
    posverbo = (int) (Math.random()*6);
    pospreposicion = (int) (Math.random()*6);
    
    
    
        
    Mayuscula= articulos1[posarticulo].charAt(0);
    System.out.println(Mayuscula);
    Mayuscula= Character.toUpperCase(Mayuscula);
    System.out.println(Mayuscula);   
    StringBuilder textoBuilder= new StringBuilder("");
    System.out.println(textoBuilder.append(articulos[posarticulo]).append("  ").append(sustantivos[possustantivo]).append("  ").append(verbos[posverbo]).append("  ").append(preposiciones[pospreposicion]).append("  ").append(articulos1[posarticulo1]).append("  ").append(sustantivos[possustantivo]).append("."));    
    }//GEN-LAST:event_btnRandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjerciciocaracteres1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjerciciocaracteres1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjerciciocaracteres1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjerciciocaracteres1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjerciciocaracteres1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRandom;
    // End of variables declaration//GEN-END:variables
}
